[package]
name = "stormtrooper"
version = "0.1.0"
authors = ["Ty Overby <ty@pre-alpha.com>"]

[dependencies.ares]
path = "../ares/"

[dependencies.notify]
path = "../rsnotify/"

[dependencies]
#notify = "2.3.3"
iron = "0.2.*"
router = "0.0.15"
typemap = "0.3.3"
